### ISSUE TITLE
【feat】手机的占用/释放建议提供单独的api，现在只有打开远控才占用手机

### ISSUE THREAD

**Issue by samuelchen2015** [SonicCloudOrg/sonic-agent#104]
手机的占用/释放建议提供单独的api，现在只有打开远控才占用手机

**Comment by samuelchen2015** [comment]
android 的占用接口，可以 参考stf，占用后返回控制端口

**Comment by ZhouYixun** [comment]
社区也有人提出 https://sonic-cloud.wiki/d/53-rest-api/6

两边进度我会同时更新，感谢
