### ISSUE TITLE
【Bug】测试套件测试结果推送数据与网页结果不一致

### ISSUE THREAD

**Issue by xuhanjian** [SonicCloudOrg/sonic-agent#106]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 
![image](https://user-images.githubusercontent.com/31010682/149498552-ee856048-8070-4484-adeb-e3e70dbb10dd.png)
![image](https://user-images.githubusercontent.com/31010682/149498610-720e6385-e245-4918-8442-1dae86d6dc88.png)
钉钉推送通过8异常2
点击链接查看结果通过9异常1

**版本**
1.2.0-release
Sonic的版本号 | Sonic's Version. 
部署的系统(mac,windows32...) |  System

**Comment by ZhouYixun** [comment]
请用最新版本试一下，另外建议现在bug提到社区里面

**Comment by ZhouYixun** [comment]
2.4.0已经解决
