### ISSUE TITLE
【启动异常】

### ISSUE THREAD

**Issue by 0x88l** [SonicCloudOrg/sonic-agent#153]
**问题描述**
前提：使用mac接入ios设备

步骤：使用命令行启动：java -Dfile.encoding=utf-8 -jar sonic-agent-macosx-x86_64.jar，系统会弹出：无法打开“sonic-go-mitmproxy”，因为  and 无法验证开发者无法打开“sonic-ios-bridge”，因为无法验证开发者
如图所示
<img width="254" alt="image" src="https://user-images.githubusercontent.com/18346467/160049481-3e455b2b-183c-4c5c-86a4-720a815020b8.png">

**版本**
Sonic的版本号 | v1.3.2-beta
部署的系统 |  MacOS

**Comment by 0x88l** [comment]
close吧，这个不是问题；通过隐私设置可以允许跳过

**Comment by ZhouYixun** [comment]
> close吧，这个不是问题；通过隐私设置可以允许跳过

嗯嗯，mac需要在隐私那边开放，有问题可以去Sonic社区提，我那边回比较快
