### ISSUE TITLE
【feat】滑动固定距离

### ISSUE THREAD

**Issue by yaming116** [SonicCloudOrg/sonic-agent#160]
场景： 一些控件可能开始不可见，需要滑动一些距离。如果直接使用控件 A->控件B，可能不可用。需要一些手段。
例如：从屏幕 x,y -> 每次横向或纵向固定移动，循环检测目标控件是否存在

**Comment by ZhouYixun** [comment]
https://sonic-cloud.cn/doc/doc-iterator.html

目前可以通过迭代空间列表实现，issue我先关闭了
