### ISSUE TITLE
agent包启动报错：chmod 777 xxx

### ISSUE THREAD

**Issue by tengfei-jiao** [SonicCloudOrg/sonic-agent#224]
agent包放在 D:\Program Files (x86) 目录下启动就会报错权限不对，换个其他目录，启动正常

**Comment by ZhouYixun** [comment]
> agent包放在 D:\Program Files (x86) 目录下启动就会报错权限不对，换个其他目录，启动正常

应该是你电脑的超管权限没覆盖到这个目录，也欢迎去用户社区反馈哦，感谢
