### ISSUE TITLE
adb的端口号是按什么规则生成的吗？还是完全随机

### ISSUE THREAD

**Issue by dddzname** [SonicCloudOrg/sonic-agent#251]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

**版本**
Sonic的版本号 | Sonic's Version. 
部署的系统(mac,windows32...) |  System

**Comment by ZhouYixun** [comment]
随机生成，这不是bug

**Comment by ZhouYixun** [comment]
不过有问题可以去社区提问哦 https://sonic-cloud.wiki/  ，github我这边比较关注pull request或者技术上的问题，使用疑问可以去社区，可以跟其他用户交流
