### ISSUE TITLE
初始化Driver失败！部分功能不可用！请联系管理员

### ISSUE THREAD

**Issue by zhouweisong** [SonicCloudOrg/sonic-agent#253]
**Bug 描述**
点击【Appium Driver】时报“初始化Driver失败！部分功能不可用！请联系管理员”

**版本**
Sonic的版本号 | V1.5.0
部署的系统(mac,windows32...) |  CentOS

**Comment by ZhouYixun** [comment]
这不是bug，欢迎去社区提问或者查找其他用户踩坑记录哦 https://sonic-cloud.wiki/

github这边偏向看技术问题
