### ISSUE TITLE
[Bug] 最新代码在windows上启动会报错

### ISSUE THREAD

**Issue by hotsmile** [SonicCloudOrg/sonic-agent#351]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

版本为2.5.2

### Deploy platform

windows 10

### Minimal reproduce step

启动的时候，报错,主要原因为 envchecktool.java改动了,只判断了可执行文件，缺乏对windows的支持

 Check ADB environment Fail ×
· Missing file! Please ensure that `adb` command useful or `plugins` folders (containing adb) in the current directory
=========================== Check results ===========================
× Unfortunately, some of the check items did not pass!
· System: windows 10
· ADB version: unknown
· sonic-android-supply version: unknown
· sonic-ios-bridge version: unknown
· sonic-go-mitmproxy version: unknown
========================== Check Completed ==========================

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
这块还没发版呢，昨晚提交的新代码而且默认先拿ANDROID_HOME的配置，没有才判断二进制文件的，你确认下？

**Comment by ZhouYixun** [comment]
```
 private boolean checkADB() {
        String type = "Check ADB environment";
        printChecking(type);
        String path = System.getenv("ANDROID_HOME");
        if (path != null) {
            path += File.separator + "platform-tools" + File.separator + "adb";
        } else {
            path = "plugins" + File.separator + "adb";
        }
        File adb = new File(path);
        if (adb.exists()) {
            adb.setExecutable(true);
            adb.setWritable(true);
            adb.setReadable(true);
            List<String> ver = ProcessCommandTool.getProcessLocalCommand(String.format("%s version", adb.getAbsolutePath()));
            if (ver.size() == 0) {
                printFail(type);
                throw new RuntimeException("Can not use adb! Please ensure that `adb` command useful!" + (system.toUpperCase(Locale.ROOT).contains("MAC") ? " You can see " + HELP_URL + " ." : ""));
            } else {
                adbVersion = ver.get(0);
                printPass(type);
                return true;
            }
```

这里我是跟旧逻辑一致的，先拿本地的 $ANDROID_HOME/platform-tools/adb，没有才从plugins下面拿，当然这个还没发版，现在plugins下面还没有。你这边再试一下？

**Comment by hotsmile** [comment]
**社区我这边访问不了，社区现在是正常的吗？https://sonic-cloud.wiki/**

**Comment by hotsmile** [comment]
> ```
>  private boolean checkADB() {
>         String type = "Check ADB environment";
>         printChecking(type);
>         String path = System.getenv("ANDROID_HOME");
>         if (path != null) {
>             path += File.separator + "platform-tools" + File.separator + "adb";
>         } else {
>             path = "plugins" + File.separator + "adb";
>         }
>         File adb = new File(path);
>         if (adb.exists()) {
>             adb.setExecutable(true);
>             adb.setWritable(true);
>             adb.setReadable(true);
>             List<String> ver = ProcessCommandTool.getProcessLocalCommand(String.format("%s version", adb.getAbsolutePath()));
>             if (ver.size() == 0) {
>                 printFail(type);
>                 throw new RuntimeException("Can not use adb! Please ensure that `adb` command useful!" + (system.toUpperCase(Locale.ROOT).contains("MAC") ? " You can see " + HELP_URL + " ." : ""));
>             } else {
>                 adbVersion = ver.get(0);
>                 printPass(type);
>                 return true;
>             }
> ```
> 
> 这里我是跟旧逻辑一致的，先拿本地的 $ANDROID_HOME/platform-tools/adb，没有才从plugins下面拿，当然这个还没发版，现在plugins下面还没有。你这边再试一下？

windows 下, adb可执行文件是带有adb.exe 所以你取不到adb的path

**Comment by ZhouYixun** [comment]
原来如此，我兼容一下，感谢反馈

**Comment by ZhouYixun** [comment]
> **社区我这边访问不了，社区现在是正常的吗？https://sonic-cloud.wiki/**

社区可以访问的

**Comment by ZhouYixun** [comment]
你好，方便在 https://github.com/SonicCloudOrg/sonic-agent/tree/feat/v3.0 这个分支上验证一下吗

**Comment by hotsmile** [comment]
> 你好，方便在 https://github.com/SonicCloudOrg/sonic-agent/tree/feat/v3.0 这个分支上验证一下吗？我修了一下 @hotsmile

你只改了一个点

· sonic-android-supply version: unknown
· sonic-ios-bridge version: unknown
· sonic-go-mitmproxy version: unknown
这三个还没有改。

**Comment by ZhouYixun** [comment]
> > 你好，方便在 https://github.com/SonicCloudOrg/sonic-agent/tree/feat/v3.0 这个分支上验证一下吗？我修了一下 @hotsmile
> 
> 你只改了一个点
> 
> · sonic-android-supply version: unknown · sonic-ios-bridge version: unknown · sonic-go-mitmproxy version: unknown 这三个还没有改。

一并改了呀

**Comment by ZhouYixun** [comment]
开发环境这三个插件要自己下载哦，可以看官网开发文档
