### ISSUE TITLE
[Question] 导入IntntelliJ IDEA 环境下，提示找不到包

### ISSUE THREAD

**Issue by zcq111** [SonicCloudOrg/sonic-agent#395]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.3

### Deploy platform

Windows 10

### Minimal reproduce step

步骤：
1、打开ideal，打开项目sonic-agent
2、打开pom.xml
3、提示Dependency 'com.android.tools.ddms:ddmlib:31.0.0' not found 

<dependency>
<groupId>com.android.tools.ddms</groupId>
<artifactId>ddmlib</artifactId>
<version>31.0.0</version>
</dependency>

4、Maven栏 Dependencies 提示红色波浪线

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！
![微信图片_20231227175032](https://github.com/SonicCloudOrg/sonic-agent/assets/39423986/b159654c-d19d-4c02-a383-76b8e1b8276b)

**Comment by ZhouYixun** [comment]
无法复现，可以检查下你的maven仓库地址
