### ISSUE TITLE
uiautomator2运行异常

### ISSUE THREAD

**Issue by gi13371** [SonicCloudOrg/sonic-agent#403]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.0.7

### Deploy platform

linux

### Minimal reproduce step

自动化测试的时候偶现的，安卓客户端报io.appium.uiautomator2（也可能是.test）停止运行，日志看不到uiautomator2的报错，请问在哪里能看到uiautomator2的错误日志信息呢，或者这个报错是否有通用解决方式？

**Comment by ZhouYixun** [comment]
这个问题应该在 https://github.com/appium/appium-uiautomator2-server 提问，附上你的现象和版本号

**Comment by gi13371** [comment]
> 这个问题应该在 https://github.com/appium/appium-uiautomator2-server 提问，附上你的现象和版本号

感谢回复，那请问sonic项目有对uiautomator2进行定制吗，如果没有请问用到的是appium-uiautomator2-server哪个版本呢？

**Comment by ZhouYixun** [comment]
> > 这个问题应该在 https://github.com/appium/appium-uiautomator2-server 提问，附上你的现象和版本号
> 
> 感谢回复，那请问sonic项目有对uiautomator2进行定制吗，如果没有请问用到的是appium-uiautomator2-server哪个版本呢？

没有，你看版本号
