### ISSUE TITLE
[Bug] linux的jar版本会报no jniopencv_highgui in java.library.path:的错误，Docker版没问题

### ISSUE THREAD

**Issue by wanyaxing** [SonicCloudOrg/sonic-agent#405]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic-agent : 2.6.3 ,服务端也是2.6.3

### Deploy platform

两台机器：

Linux sz-xr3601-18 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Linux wanyaxing 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Minimal reproduce step

使用以下自定义脚本代码：
`
import org.cloud.sonic.vision.cv.SIFTFinder;

SIFTFinder siftFinder = new SIFTFinder();
siftFinder.getSIFTFindResult(androidStepHandler.getScreenToLocal(), androidStepHandler.getScreenToLocal(), true);
`
在mac版或PC版的agent都可以正常运行，但linux版却不能运行，且同样的代码执行两次，报的错误也不一样。

第一次说：
Script errorjava.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path: /usr/lib/x86_64-linux-gnu/

第二次说：
Script errorjava.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.opencv.opencv_features2d.SIFT

我已经试了好多种方案，都是类似错误，比较迷茫，也搜索了很多资料，甚至都没发现别人遇到这位，我甚至单独新部署了ubuntu的全新系统，也是以上错误，真是非常奇怪，我该如何做呢？

![iShot_2024-01-18_20 24 43](https://github.com/SonicCloudOrg/sonic-agent/assets/7940795/16debeeb-6f68-4b8a-bbc4-b780ba0db889)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by wanyaxing** [comment]
PC 版本同样的代码就没问题。

![image](https://github.com/SonicCloudOrg/sonic-agent/assets/7940795/d520135f-01bd-48bc-8147-af4903e85940)

**Comment by ZhouYixun** [comment]
像是打包时候的依赖问题，但是linux我建议直接用docker部署应该会好一点？

**Comment by ZhouYixun** [comment]
试下docker部署能不能解决

**Comment by ZhouYixun** [comment]
> 好，我继续去试docker化下效果。 但本身打包也请帮看下，因为我这边已经实际有部署了，再转docker代价会比较大（版本升级会相对容易些）

不是，我们有官方Agent的Docker版本，直接用就行，不用你自己打docker镜像

**Comment by wanyaxing** [comment]
docker下可以正常执行。

![image](https://github.com/SonicCloudOrg/sonic-agent/assets/7940795/22180314-974d-444d-8db8-c1fbe2c9ea6e)

**Comment by ZhouYixun** [comment]
> docker下可以正常执行。
> 
> ![image](https://private-user-images.githubusercontent.com/7940795/298012281-22180314-974d-444d-8db8-c1fbe2c9ea6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTYwMDcsIm5iZiI6MTcwNTY1NTcwNywicGF0aCI6Ii83OTQwNzk1LzI5ODAxMjI4MS0yMjE4MDMxNC05NzRkLTQ0NGQtOGRiOC1jMWZiZTJjOWVhNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDkxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYyMTZjY2EzMzg0ZDQ1ZjgyMGUyYTcxMTgzNjJkYTQ1YzMzM2Q4Yzg0ODRjMzUwZjk3NGYzYTVjZTQyZmNkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.euf600znx-aQrnxKw43fJN--75deJXhsd__v6UsdryY)

那似乎是纯净的Linux系统丢了某些图像识别的必要依赖，这个排查还挺不好搞，你先用着Docker版本吧

**Comment by ZhouYixun** [comment]
你也可以看下这里 https://github.com/SonicCloudOrg/sonic-dockerfile/blob/main/sonic-agent/Dockerfile

按着dockerfile安装下依赖

**Comment by wanyaxing** [comment]
好的，的确，我尝试把docker里的jar拉出来，发现是一样的。
那就只能慢慢排查对比环境了。。。

**Comment by wanyaxing** [comment]
在部署的测试环境Ubuntu里，我通过安装libgtk2.0-dev后，恢复正常了。
sudo apt-get -qqy --no-install-recommends install libgtk2.0-dev

然而回到最初环境，就是5.14.0-284.11.1.el9_2.x86_64这个，应该是Red Hat Enterprise Linux 9.2?(是以前同事搞的），这个系统没有libgtk2.0-dev可以装，好懵逼。。。。

有什么建议么

**Comment by ZhouYixun** [comment]
> 在部署的测试环境Ubuntu里，我通过安装libgtk2.0-dev后，恢复正常了。 sudo apt-get -qqy --no-install-recommends install libgtk2.0-dev
> 
> 然而回到最初环境，就是5.14.0-284.11.1.el9_2.x86_64这个，应该是Red Hat Enterprise Linux 9.2?(是以前同事搞的），这个系统没有libgtk2.0-dev可以装，好懵逼。。。。
> 
> 有什么建议么

red hat 很少人用吧，都是ubuntu来部署Agent好一点

**Comment by wanyaxing** [comment]
OK，那就只好干大活了，全部重刷。
