### ISSUE TITLE
[Bug] 小米13pro touch事件触发后投屏没反应

### ISSUE THREAD

**Issue by chenshuai12** [SonicCloudOrg/sonic-agent#414]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.4

### Deploy platform

windows10

### Minimal reproduce step

连接小米13pro，点击马上使用，点击网页投屏的任意app，无法进入
调试发现：
SonicPluginTouchService 启动时， AndroidTouchHandler 233行返回的结果 为 null，导致 touchSocketThread 获取锁超过20此后，socket 没有创建。touch 事件 触发时，没有输出流

2024-03-01 14:59:18.737 - INFO 18644 --- [http-nio-7777-exec-9] o.c.s.agent.websockets.AndroidWSServer   : AndroidWSServer-*** send: {"detail":"up\n","type":"touch"}
2024-03-01 14:59:18.737 - INFO 18644 --- [http-nio-7777-exec-9] o.c.s.a.t.handlers.AndroidTouchHandler   : *** write output stream is null.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
安卓版本是多少

**Comment by chenshuai12** [comment]
> 安卓版本是多少

14

**Comment by ZhouYixun** [comment]
Agent的版本也是2.6.4? 看看sonic.apk的版本是多少

**Comment by chenshuai12** [comment]
> Agent的版本也是2.6.4? 看看sonic.apk的版本是多少

搞错了，agent是2.6.3，sonic.apk没有改过，代码拉下来的就是这个apk，我换最新的试试？

**Comment by ZhouYixun** [comment]
可以看新版本公告，2.6.4修复了
