### ISSUE TITLE
[Bug] 这个帖子链接打不开了 Q2: 使用后没有出现画面，但是按键操作正常。  A1: 解决方案可参考 这个帖子。

### ISSUE THREAD

**Issue by PeiZhiFei** [SonicCloudOrg/sonic-agent#417]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

这个帖子链接打不开了

### Deploy platform

这个帖子链接打不开了

### Minimal reproduce step

这个帖子链接打不开了

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
旧社区已经关闭了，现在可以从官网的用户社区进入新社区
