### ISSUE TITLE
[Feature] 测试中不能查看远程真机画面，无法查看自动化的情况

### ISSUE THREAD

**Issue by jeniva** [SonicCloudOrg/sonic-agent#421]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4 

### Deploy platform

Linux

### Minimal reproduce step

1.在测试套件里面勾选手机执行自动化，查看报告里面没有截图和画面
2.点击设备中心查看，提示测试中，但是无法得知画面是否正常，特别是安装应用如果有弹窗没自动化处理的情况下，手动也无法解决。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
这不是bug，设计初衷也不是这样，如果你有需要可以自行考虑二开
