### ISSUE TITLE
[Bug] 应用安装没有进度，有时候会安装失败

### ISSUE THREAD

**Issue by jeniva** [SonicCloudOrg/sonic-agent#423]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.4

### Deploy platform

Linux

### Minimal reproduce step

1.界面上面安装应用没有进度提示，有时候都不知道安装成功了没有
2.批量执行自动化的时候有时候会出现一些手机安装成功，一些没有成功，盲猜是没有下载全，可能批量下载这块是不是可以优化一下
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/f9ab0dde-0377-42cf-b609-f41967a19fa2)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你下载链接都不是.apk结尾，这不算是sonic问题吧，不过你想处理各种异常情况也是可以的，不过这不是bug

**Comment by jeniva** [comment]
> 你下载链接都不是.apk结尾，这不算是sonic问题吧，不过你想处理各种异常情况也是可以的，不过这不是bug

我截图没截取全，批量安装，有些安装成功了，有些提示失败
