### ISSUE TITLE
Android6设备使用minicap黑屏，scrcpy正常

### ISSUE THREAD

**Issue by Barry413** [SonicCloudOrg/sonic-agent#424]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.2.1

### Deploy platform

windows10

### Minimal reproduce step

因为scrcpy截取屏幕图片很慢，所以考虑切换使用minicap,但是在Android6设备使用minicap黑屏，Android10设备使用minicap正常

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你可以提issue给minicap官方
