### ISSUE TITLE
[Bug] 自定义脚本，全局参数赋值之后，值没有变化。

### ISSUE THREAD

**Issue by lzbxqmy** [SonicCloudOrg/sonic-agent#425]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.4

### Deploy platform

Linux

### Minimal reproduce step

【操作步骤】
1、测试数据管理->全局参数页面，创建参数名为"mobile"，值为"111"；
2、测试步骤里，自定义脚本如下：
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
String stringMobile = "{\"mobile\":\"333\"}";
JSONObject jsonMobile =  JSON.parseObject(stringMobile);
androidStepHandler.setGlobalParams(jsonMobile);
3、运行脚本测试步骤。
【问题】
查看全局参数，mobile的值仍然是“111”，没有修改成功。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by YeungHoiChiu** [comment]
> String stringMobile = "{"mobile":"333"}";

这样能成功就有鬼了
