### ISSUE TITLE
[Help]  agent启动后显示hub is not ready. ignore

### ISSUE THREAD

**Issue by FullCat** [SonicCloudOrg/sonic-agent#432]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.1

### Deploy platform

windows10

### Minimal reproduce step

windows端直接部署agent, 可以连接到server, 但是远程真机是 图像不显示，看日志是显示hub is not ready. ignore
<img width="1490" alt="image" src="https://github.com/SonicCloudOrg/sonic-agent/assets/9285521/be021577-8325-4dbf-b3e5-70f9d52c3afa">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by caixusheng123** [comment]
遇到了同样的问题，请问已经解决了吗

**Comment by caixusheng123** [comment]
agent 除了这个没有其他的报错信息，appium也运行正常，通过python-client可以正常调用

**Comment by ZhouYixun** [comment]
这个提示不影响使用的，是正常的日志

**Comment by liuxinpy** [comment]
这个问题解决了吗，我也是一模一样的，windows打开sonic连接，可以连接到服务器，但是远程真机是图像不显示。看日志也是输出的这个

**Comment by liuxinpy** [comment]
可以了，是wda的问题，少了一步，需要开发者验证

**Comment by liuxinpy** [comment]
> 这个提示不影响使用的，是正常的日志

我也遇到了，可以了，是wda的问题，少了一步，需要开发者验证。
