### ISSUE TITLE
[Bug] 安卓「华为、OPPO」获取控件元素报错，小米手机是OK的

### ISSUE THREAD

**Issue by liuguangyong93** [SonicCloudOrg/sonic-agent#434]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic-agent & sonic-server & sonic-web version：V2.6.4
sonic-driver-core version：V1.1.29

### Deploy platform

macos本地运行SonicWeb、SonicServer、SonicAgent，系统版本：Sonoma V14.4.1

### Minimal reproduce step

本地运行SonicWeb、SonicServer、SonicAgent三个服务，连接华为 or OPPO手机，获取可以连接成功，但是在获取控件元素后，报以下异常「小米手机正常」，我也在尝试解决修复，但是进度可能稍慢，还请大佬们帮忙看一下！

![image](https://github.com/SonicCloudOrg/sonic-agent/assets/15274523/52bf5341-2e77-4f18-8c4a-9cf37d5ed7ba)
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/15274523/9b7d244c-403c-4014-8f5a-716594f3334c)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
按照文档关闭一些电量优化和打开系统的权限，大体都是系统把uia2进程干掉了
