### ISSUE TITLE
[Bug] 是否有计划针对 iOS17 设备修改 wda 的启动和调用逻辑？

### ISSUE THREAD

**Issue by wangier** [SonicCloudOrg/sonic-agent#437]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

iOS17 不再支持xcrunner 独立启动了，需要通过 xcodebuild 从代码启动，或者通过 xcrun 启动已安装的 xctest runner。
有计划针对 iOS17 进行修改吗？

### Deploy platform

macOS 14.4.1

### Minimal reproduce step

连接 iOS17 设备

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR! | 我将发起PR！

**Comment by wangier** [comment]
> 同问，什么时候能支持iOS7呢

我把这个问题解决了，但是是权限提交上去

**Comment by ropon** [comment]
如何解决的呢

**Comment by wangier** [comment]
> 如何解决的呢

iOS17不能直接通过现在版本的sib运行xcrunner，必须通过执行 xcrun devicectl device process launch 的方式启动xcrunner

**Comment by sam80180** [comment]
I have managed to do it on Linux with the help of other great tools.
Here are my steps:

1. Run `go-ncm` in background.
   https://github.com/danielpaulus/go-ios/tree/main/ncm
   
2. Run `go-ios tunnel start` in background.
   https://github.com/danielpaulus/go-ios

3. Connect your device(s), wait until you see `go-ios` says tunnel(s) are established.

4. Mount personalized image using `t3 -u xxxxxx exec mounter auto-mount`.
   https://github.com/doronz88/pymobiledevice3

5. Start WDA using `go-ios --udid xxxxxx runwda`.
