### ISSUE TITLE
【错误或体验】网络抓包时，Google Play无法联网；网络抓包没有停止功能。

### ISSUE THREAD

**Issue by Android-Freshman** [SonicCloudOrg/sonic-agent#440]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

Sonic版本：2.6.4

### Deploy platform

服务器：Mac上的虚拟机，CentOS 7.9，内核版本：5.4.230-1.el7.elrepo.x86_64，内网IP：192.168.1.253
Agent： Mac OS 11.7.10
手机：   三星Galaxy A8 GM-A530N，Android 9, API 28，三星官方系统

### Minimal reproduce step

启动网络抓包后，Google Play无法联网。
前端页面：请增加停止网络抓包功能

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
有的呀，前端有一个按钮停止代理
