### ISSUE TITLE
[Help] 安卓APP 使用“控件元素”只能获取到 原生控件，获取不到内嵌的H5控件，请大佬帮忙看看怎么解决，谢谢

### ISSUE THREAD

**Issue by morningfine** [SonicCloudOrg/sonic-agent#442]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

Ubuntu 20

### Minimal reproduce step

![image](https://github.com/SonicCloudOrg/sonic-agent/assets/41957446/fc107309-9396-4bb3-b846-8188d611514a)
安卓APP 使用“控件元素”只能获取到 原生控件，获取不到内嵌的H5控件，请大佬帮忙看看怎么解决，谢谢

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by FullCat** [comment]
遇到了同样的问题，请问解决了吗，还有造成这种问题的原因是什么呢

**Comment by YeungHoiChiu** [comment]
webview 使用网页调试，使用文档有说明的

**Comment by ZhouYixun** [comment]
> webview 使用网页调试，使用文档有说明的

这个小伙伴的回答就是正确答案哦
