### ISSUE TITLE
使用无线调试的时候，uia返回超时，使用postman请求，一个请求要两百多秒才返回。

### ISSUE THREAD

**Issue by zzu402** [SonicCloudOrg/sonic-agent#446]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

window10

### Minimal reproduce step

1.使用无限调试匹配码匹配app
2.使用连接uia，首次正常连接。
3.uia请求第二次之后连接超时。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
无线调试我没测试过，sonic还是更适用usb连接的
