### ISSUE TITLE
[Bug] 远程控制页面开始性能监控后，点击停止监控没有效果

### ISSUE THREAD

**Issue by gzhtest** [SonicCloudOrg/sonic-agent#467]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.7.1

### Deploy platform

Windows 10

### Minimal reproduce step

①点击开始监控
![image](https://github.com/user-attachments/assets/84634c22-ac57-4030-8ad4-88e53ff461b9)
②点击停止监控
![image](https://github.com/user-attachments/assets/a2f1e6f2-0c69-4fc1-bcee-54aa1f437fa6)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-agent/pull/468
