### ISSUE TITLE
[Bug] ios 设备滑动报错 waitForQuiescenceIncludingAnimationsIdle

### ISSUE THREAD

**Issue by Rladmsrl** [SonicCloudOrg/sonic-agent#469]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.7.1

### Deploy platform

macos

### Minimal reproduce step

连接设备后滑动就会报错 ios16 ios17 都会
![screenshot-20240924-163431](https://github.com/user-attachments/assets/1b99b929-9242-4eca-ab13-db1eb54727c6)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by Rladmsrl** [comment]
就是咱们 git 的 wda

**Comment by ZhouYixun** [comment]
看看还有没有人遇到，我这边复现不了

**Comment by Rladmsrl** [comment]
好的谢谢

**Comment by ZhouYixun** [comment]
已经解决了，更新到最新wda和最新sonic可以解决

**Comment by riginnnn** [comment]
是解决了 但是我这边TouchAction的方法用不了了... 看样子要替换成w3c的才可以
