### ISSUE TITLE
[bug]  org.cloud.sonic.driver.common.tool.SonicRespException: org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.. Try changing the 'enforceXPath1' driver setting to 'true' in order to workaround the problem.","rid":0,"udId":"R5CW8091P0X","status":3,"cid":0

### ISSUE THREAD

**Issue by lyc10031** [SonicCloudOrg/sonic-agent#472]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.7.1 

### Deploy platform

maxos 

### Minimal reproduce step

操作点击控件失败，提示:

 {"msg":"step","des":"点击Android-开播-video 类型 Effects 异常！","log":"点击xpath: //android.widget.TextView[contains(@text,'Effects')]","rid":0,"udId":"R5CW8091P0X","status":4,"cid":0}
 
 {"msg":"step","des":"","log":"异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.. Try changing the 'enforceXPath1' driver setting to 'true' in order to workaround the problem.","rid":0,"udId":"R5CW8091P0X","status":3,"cid":0}

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
重复
