### ISSUE TITLE
[Bug] iOS需要输入enable UI自动化的手机密码，即使在设置-开发者-打开自动化按钮，还是会要求输入密码

### ISSUE THREAD

**Issue by Pycoder0901** [SonicCloudOrg/sonic-agent#474]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

最新

### Deploy platform

iOS 16

### Minimal reproduce step

 iOS需要输入enable UI自动化的手机密码，即使在设置-开发者-打开自动化按钮，还是会要求输入密码

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
取消手机的密码不就好了
