### ISSUE TITLE
[Bug] 在mac上用docker命令启动前后端服务，提示image的版本与操作系统不一致，如何解决？

### ISSUE THREAD

**Issue by tlqiao** [SonicCloudOrg/sonic-agent#476]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.7.2

### Deploy platform

mac，m1芯片

### Minimal reproduce step

本地已经安装mysql数据库，.env中已经设置的数据库的用户名密码等信息，用docker-compose up -d命令启动前后端服务，提示
sonic-server-gateway The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested。其他image也在报相同的提示。

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
不适配m1芯片的，建议server还是部署到linux服务器上面比较正规
