### ISSUE TITLE
关闭定时任务，而后操作远程控制，返回再次执行测试套件出现报错：“发生了未知异常”无法执行测试用例【Bug】

### ISSUE THREAD

**Issue by lilingqian** [SonicCloudOrg/sonic-agent#70]
**Bug 描述**
关闭定时任务，操作远程控制，返回再次执行测试套件失败，无法执行测试用例。
详细描述：
执行测试套件失败，angent端log无任何打印，测试结果增加一条运行中... 貌似之前报错后没有恢复正常，重启电脑，重新部署未恢复.
**版本**
Sonic的版本号 | Sonic's Version.   版本号：v1.2.0-beta3
部署的系统(mac,windows32...) |  System。：mac。系统版本：os11.4 
<img width="1208" alt="agent报错log" src="https://user-images.githubusercontent.com/32317178/144832504-8fa371f5-ada8-43fc-9f37-9e8ea87cba29.png">

**Comment by ZhouYixun** [comment]
请提供simple的日志

**Comment by ZhouYixun** [comment]
已经私下沟通确认无法复现，重启后无出现这个情况，我先关闭。
如果你再复现的话，可以reopen这个issue~

**Comment by ZhouYixun** [comment]
已确认是另一个bug引起的，下版本修复~~
