### ISSUE TITLE
【Bug】跑UI自动化时，使用图像定位并点击，会报“SIFT算法无法定位图片，切换AKAZE算法中...”等，复现几率50%左右，如图

### ISSUE THREAD

**Issue by gengjikun** [SonicCloudOrg/sonic-agent#75]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

**版本**
Sonic的版本号 | Sonic's Version. 
部署的系统(mac,windows32...) |  System
![image](https://user-images.githubusercontent.com/16043342/146487355-cd64ed5b-911a-4f58-88d8-f2edb4bece33.png)

**Comment by ZhouYixun** [comment]
这个是你的图片不够“特殊”，如果是卡通人物等等图片类型越复杂，识别正确率越高。你这个图片可能还是简单了
