### ISSUE TITLE
【Bug】mac10.14.6系统上，adbkit启动失败，导致adb远程无法使用

### ISSUE THREAD

**Issue by Rx2DD** [SonicCloudOrg/sonic-agent#80]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

adbkit启动失败导致adb远程无法使用，adb devices显示offline（已定位问题，adbkit指令未加引号导致）

**版本**
Sonic的版本号 | Sonic's Version. 
v1.2.0-release
部署的系统(mac,windows32...) |  System
mac 10.14.6

**Comment by ZhouYixun** [comment]
经沟通和排查是bug，下版本修复
