### ISSUE TITLE
【Bug】多台设备用例批跑后无法连接远程机器

### ISSUE THREAD

**Issue by xuhanjian** [SonicCloudOrg/sonic-agent#81]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 
使用19台设备批跑用例，用例执行完成购无法远控测试机器，重启Agent后解决

**版本**
Sonic的版本号 | Sonic's Version. 
1.2.0 release
部署的系统(mac,windows32...) |  System
linux

**Comment by JayWenStar** [comment]
可以提供下启动参数吗

**Comment by JayWenStar** [comment]
可能是adbkit的问题

**Comment by ZhouYixun** [comment]
请提供日志信息
