### ISSUE TITLE
【Bug】长时间连接的机器重新连接远控提示初始化driver失败

### ISSUE THREAD

**Issue by xuhanjian** [SonicCloudOrg/sonic-agent#82]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

**版本**
Sonic的版本号 | Sonic's Version. 
1.2.0-release

部署的系统(mac,windows32...) |  System
linux
![image](https://user-images.githubusercontent.com/31010682/147178360-df1fc281-fc22-4ba5-adc1-3346f502fef2.png)
![image](https://user-images.githubusercontent.com/31010682/147178603-8fdde767-bb55-4c8f-ab92-d71c4ff60788.png)

**Comment by JayWenStar** [comment]
应该已修复，等下个版本试试：https://github.com/SonicCloudOrg/sonic-server/issues/100

**Comment by ZhouYixun** [comment]
预计是刷新socket引起的，可以尝试明天的v1.3.0-beta1

**Comment by ZhouYixun** [comment]
已确认另一个bug引起的，下版本修复~~

**Comment by xuhanjian** [comment]
升级到1.3.0版本早上用完下午素有机器连接又报driver初始化失败-_- @ZhouYixun

**Comment by xuhanjian** [comment]
[sonic-agent.log](https://github.com/SonicCloudOrg/sonic-agent/files/7911055/sonic-agent.log)

**Comment by ZhouYixun** [comment]
社区回复你
