### ISSUE TITLE
【Bug】

### ISSUE THREAD

**Issue by Felix1029** [SonicCloudOrg/sonic-agent#95]
**Bug 描述**
集群版：
adb connect 无法连接，提示
adb connect 192.168.242.130:65178
failed to authenticate to 192.168.242.130:65178

mac 防火墙已关闭

**版本**
Sonic的版本号 | Sonic's Version. v1.3.0-beta1.1
部署的系统   mac

**Comment by ZhouYixun** [comment]
已经连上了这个是，你输入adb devices就看到
