### ISSUE TITLE
【优化】固定adb远程的端口号

### ISSUE THREAD

**Issue by Rx2DD** [SonicCloudOrg/sonic-agent#96]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

固定adb远程连接的端口号，或者固定在一个区间内，方便做映射

**Comment by gaierlj** [comment]
这个特性还没支持吧？

**Comment by yaming116** [comment]
@gaierlj @Rx2DD 可以说说你们具体需要的场景么？目前设计来看一台机器只能运行一个 agent，这样端口应该需要有映射直接使用 host 模式运行即可

**Comment by ZhouYixun** [comment]
@gaierlj @Rx2DD 2.5.0可以通过rest api自定义端口了，到时候可以关注下版本更新~
