### ISSUE TITLE
【Bug】

### ISSUE THREAD

**Issue by Felix1029** [SonicCloudOrg/sonic-agent#97]
**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is. 

获取控件元素不全
![image](https://user-images.githubusercontent.com/19203666/147625362-68aac757-0332-4d51-8d17-a679a57a7de9.png)

没有获取到底部的一排导航控件，对比airtest 可以拿到

airtest：

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/19203666/147625447-80b5d0e2-8c8b-4de0-b51a-fe94f0f84e97.png">

**版本**
Sonic的版本号 | Sonic's Version.  v1.3.0-beta1.1
部署的系统 mac

**Comment by ZhouYixun** [comment]
这种是部分机型会屏蔽底下按钮，你可以直接操作右边的控件树去找，是找得到的
