### ISSUE TITLE
【Bug】部分设备获取控件会很长时间 or 失败

### ISSUE THREAD

**Issue by JayWenStar** [SonicCloudOrg/sonic-agent#99]
**Bug 描述**
部分设备触发查找控件树的逻辑会卡住很长时间，或者会失败（GET /session/:session_id/source 返回500）

**版本**
Sonic的版本号 | v1.3.0-beta1.1
部署的系统 |  all

**Comment by JayWenStar** [comment]
目前比较偶现，尝试debug排查找必现的手段

**Comment by JayWenStar** [comment]
单套件、单用例、注释掉AndroidPerfDataThread+AndroidRecordThread也会有问题，初步怀疑是driver某步操作出错了，因为sdk很多函数都是void，debug起来比较麻烦

**Comment by ZhouYixun** [comment]
如果driver层面的出错，我觉得可以先忽略了。后面我多设备跑下主流程

**Comment by ZhouYixun** [comment]
> 单套件、单用例、注释掉AndroidPerfDataThread+AndroidRecordThread也会有问题，初步怀疑是driver某步操作出错了，因为sdk很多函数都是void，debug起来比较麻烦

要不试试每台设备启动driver前都先启动个appiumserver

**Comment by JayWenStar** [comment]
> 前

看后面用户反馈吧，这期大概率是修不了的，有必要后面再长期跟下

**Comment by JayWenStar** [comment]
> 如果driver层面的出错，我觉得可以先忽略了。后面我多设备跑下主流程

看后面用户反馈吧，这期大概率是修不了的，有必要后面再长期跟下

**Comment by ZhouYixun** [comment]
> > 如果driver层面的出错，我觉得可以先忽略了。后面我多设备跑下主流程
> 
> 看后面用户反馈吧，这期大概率是修不了的，有必要后面再长期跟下

嗯嗯，我先关了，等反馈我再开吧，issue太多看得我心慌
